Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,54 @@
-name: Build Godot Project
-
-on:
-  push:
-#    paths:
-#      - 'projects/monstrous/buildTrigger.txt'
+name: 🚥 Status Checks
+on: push
 
 jobs:
-  export_game:
-    runs-on: ubuntu-latest
-    permissions: write-all
-    name: Export Game Job
+  tests:
+    name: 👀 Evaluate on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      # Don't cancel other OS runners if one fails.
+      fail-fast: false
+      matrix:
+        # Put the operating systems you want to run on here.
+        os: [ubuntu-latest, macos-latest, windows-latest]
+    env:
+      DOTNET_CLI_TELEMETRY_OPTOUT: true
+      DOTNET_NOLOGO: true
+    defaults:
+      run:
+        # Use bash shells on all platforms.
+        shell: bash
     steps:
-      - name: checkout
-        uses: actions/checkout@v4
-#      - name: install wine
-#        id: wine_install
-#        run: |
-#          sudo apt install wine64
-#          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
-#      - name: use custom editor settings
-#        run: |
-#          mkdir -p ~/.config/godot
-#          cp ~/path/to/my/editor_settings-3.tres ~/.config/godot/
-      - name: export game
-        id: export
-        uses: surfpossum/godot-export@master
+      - uses: actions/checkout@v3
+        name: 🧾 Checkout
+
+      - uses: actions/setup-dotnet@v3
+        name: 💽 Setup .NET SDK
         with:
-          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-rc2/Godot_v4.3-rc2_linux.x86_64.zip
-          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
-          relative_project_path: ./projects/monstrous # build the standard project
-          relative_export_path: ./projects/monstrous/build # move export output to this directory relative to git root
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
+          # Use the .NET SDK from global.json in the root of the repository.
+          global-json-file: global.json
+
+      - name: 📦 Restore Dependencies
+        run: dotnet restore
+
+      - uses: chickensoft-games/setup-godot@v1
+        name: 🤖 Setup Godot
         with:
-          name: Monstrous
-          path: /projects/monstrous
+          # Version must include major, minor, and patch, and be >= 4.0.0
+          # Pre-release label is optional.
+          version: 4.3.0 # also valid: 4.0.0.rc1 or 4.0.0, etc
+          # Use .NET-enabled version of Godot (the default is also true).
+          use-dotnet: true
+          # Include the Godot Export Templates (the default is false).
+          include-templates: true
+
+      - name: 🔬 Verify Setup
+        run: |
+          dotnet --version
+          godot --version
+
+      - name: 🧑‍🔬 Generate .NET Bindings
+        run: godot --headless --build-solutions --quit || exit 0
+
+      - name: 🦺 Build Projects
+        run: dotnet build
